m68k/driver: Fix BDM_STATIC-triggered compilation error
Commit 77dd3a4f627dcae4ac1eabf819f77deadb6a9782 replaced `static' by
`BDM_STATIC' in m68k/driver/bdm.c in order to be able to compile it
as user land libraries.  But compilation as a driver now breaks with :

In file included from /bdm/git/bdm/m68k/driver/linux/m68k-bdm.c:223:
/bdm/m68k/driver/linux/../bdm.c:246:5: warning: "BDM_DEVICE_IOPERM" is not defined
/bdm/m68k/driver/linux/../bdm.c:255:5: warning: "BDM_DEVICE_IOPERM" is not defined
/bdm/m68k/driver/linux/../bdm.c:264:5: warning: "BDM_DEVICE_USB" is not defined
In file included from /bdm/m68k/driver/linux/m68k-bdm.c:223:
/bdm/m68k/driver/linux/../bdm.c: At top level:
/bdm/m68k/driver/linux/../bdm.c:990: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int’
/bdm/m68k/driver/linux/../bdm.c:1091: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int’
/bdm/m68k/driver/linux/../bdm.c:1111: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int’
/bdm/m68k/driver/linux/../bdm.c:1316: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int’
/bdm/m68k/driver/linux/../bdm.c:1343: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int’
make[4]: *** [/bdm/m68k/driver/linux/m68k-bdm.o] Error 1

Fix that by :

- #define BDM_STATIC static in bdm.c if it is not defined
- only emit prototypes for bdm_open et al. in bdm.h #ifdef BDM_USERLAND_LIB
- add -DBDM_USERLAND_LIB to AM_CFLAGS for userland libraries compilation
- checking for #ifdef BDM_DEVICE_IOPERM/USB instead of #if
- always compile bdm-cpu32.c and bdm-cf-pe.c #ifndef BDM_USERLAND_LIB

Signed-off-by: Philippe De Muyter <phdm@macqel.be>